Fix ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -83,3 +83,21 @@ jobs:
 
       - name: Run Integration Tests (${{ matrix.provider }})
         run: dotnet test Src/Backend/TaskMaster.Test.IntegrationTests --no-build --verbosity normal
+        
+    ci-success:
+        name: CI
+        runs-on: ubuntu-latest
+        needs: build-and-test
+
+        if: ${{ always() }}
+
+        steps:
+          - name: Check CI result
+            if: ${{ needs.build-and-test.result != 'success' }}
+            run: |
+                echo "Build and test failed."
+                echo "build-and-test result: ${{ needs.build-and-test.result }}"
+                exit 1
+
+          - name: CI successful
+            run: echo "All CI checks passed."
